#!/bin/sh -ex

set ${DJANGO_PASS:=turnkey}

DB_NAME=django
DB_USER=django
DB_PASS=$(mcookie)

DJANGO_DIR=/var/www/turnkey_project
DJANGO_USER=admin
DJANGO_EMAIL=root@localhost

# convenience execution variables
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# start mysql server
/etc/init.d/mysql start

# create database
$MYSQL_ADMIN create $DB_NAME --default-character-set=utf8;

# create database user with privileges on the database
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# update database configuration password
CONF=$DJANGO_DIR/settings.py
sed -i "s|PASSWORD.*|PASSWORD\': \'$DB_PASS\',|" $CONF

# synchronize django database (mysql and sqlite)
$DJANGO_DIR/manage.py syncdb --noinput
DEVELOPMENT=y $DJANGO_DIR/manage.py syncdb --noinput

# create django superuser account
cat>>$DJANGO_DIR/create_superuser.py<<EOF
import os, settings
os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'
from django.contrib.auth.models import User
User.objects.create_superuser('$DJANGO_USER', '$DJANGO_EMAIL', '$DJANGO_PASS')
EOF
python $DJANGO_DIR/create_superuser.py
DEVELOPMENT=y python $DJANGO_DIR/create_superuser.py

rm $DJANGO_DIR/create_superuser.py

# setup admin media
ln -s /usr/share/python-django-common/django/contrib/admin/static/admin/ $DJANGO_DIR/static/admin

# configure tkl-webcp
WEBROOT=$DJANGO_DIR/media

for dir in js css images; do
    mkdir -p $DJANGO_DIR/static/$dir
    cp -a /var/www/$dir/* $DJANGO_DIR/statis/$dir
    rm -rf /var/www/$dir
done
rm -f /var/www/index.html

#symlink django-admin.py so it is avaialble everywhere (convienience)
ln -s /usr/lib/python2.7/dist-packages/django/bin/django-admin.py /usr/local/bin/django-admin.py

# apache configuration
a2dissite 000-default
a2ensite django

# stop mysql server
/etc/init.d/mysql stop
