#!/bin/bash -e
# regenerate django secret key and mysql password

. /etc/default/inithooks

updateconf() {
    CONF=/var/www/project/settings.py
    sed -i "s/^$1 = \(.*\)/$1 = \'$2\'/" $CONF
}

updateconf 'SECRET_KEY' $(mcookie)$(mcookie)

PASSWORD=$(mcookie)
updateconf 'DATABASE_PASSWORD' $PASSWORD
$INITHOOKS_PATH/bin/mysqlconf.py --user=django_user --pass="$PASSWORD"


