#!/bin/bash -e
# regenerate django secret key and mysql password

. /etc/default/inithooks

SETTINGS=/var/www/turnkey_project/turnkey_project/settings.py

SECRET_KEY=""
size=${#SECRET_KEY}
while [ $size -lt 64 ]; do
    SECRET_KEY="$SECRET_KEY$(openssl rand 64 | tr -dc 'A-Za-z0-9!$%()+,-.:;<=>?@[]^_{}~')"
    size=${#SECRET_KEY}
done
SECRET_KEY=$(echo $SECRET_KEY | cut -c1-64)

sed -i "s|SECRET_KEY.*|SECRET_KEY = \'$SECRET_KEY\'|" $SETTINGS

PASSWORD=$(mcookie)
sed -i "s|PASSWORD.*|PASSWORD\': \'$PASSWORD\',|" $SETTINGS
$INITHOOKS_PATH/bin/mysqlconf.py --user=django --pass="$PASSWORD"

