#!/bin/bash -e
# regenerate django secret key and mysql password

. /etc/default/inithooks

SETTINGS=/var/www/project/settings.py

SECRET_KEY=$(mcookie)$(mcookie)
sed -i "s|SECRET_KEY.*|SECRET_KEY = \'$SECRET_KEY\'|" $SETTINGS

PASSWORD=$(mcookie)
sed -i "s|PASSWORD.*|PASSWORD\': \'$PASSWORD\',|" $SETTINGS
$INITHOOKS_PATH/bin/mysqlconf.py --user=django --pass="$PASSWORD"

